// Common SIC codes for solar/electrical installers and related trades
// Full list: https://resources.companieshouse.gov.uk/sic/
export const SIC_CODES: Record<string, string> = {
  "27110": "Manufacture of electric motors, generators, transformers",
  "27120": "Manufacture of electricity distribution and control apparatus",
  "27200": "Manufacture of batteries and accumulators",
  "27400": "Manufacture of electric lighting equipment",
  "27510": "Manufacture of electric domestic appliances",
  "27900": "Manufacture of other electrical equipment",
  "28290": "Manufacture of other general-purpose machinery",
  "33140": "Repair of electrical equipment",
  "33200": "Installation of industrial machinery and equipment",
  "35110": "Production of electricity",
  "35120": "Transmission of electricity",
  "35130": "Distribution of electricity",
  "35140": "Trade of electricity",
  "35300": "Steam and air conditioning supply",
  "41100": "Development of building projects",
  "41201": "Construction of commercial buildings",
  "41202": "Construction of domestic buildings",
  "42110": "Construction of roads and motorways",
  "42210": "Construction of utility projects for fluids",
  "42220": "Construction of utility projects for electricity and telecoms",
  "43110": "Demolition",
  "43120": "Site preparation",
  "43210": "Electrical installation",
  "43220": "Plumbing, heat and air-conditioning installation",
  "43290": "Other construction installation",
  "43310": "Plastering",
  "43320": "Joinery installation",
  "43330": "Floor and wall covering",
  "43341": "Painting",
  "43342": "Glazing",
  "43390": "Other building completion and finishing",
  "43910": "Roofing activities",
  "43991": "Scaffold erection",
  "43999": "Other specialised construction activities n.e.c.",
  "45111": "Sale of new cars and light motor vehicles",
  "46140": "Agents involved in the sale of machinery and industrial equipment",
  "46430": "Wholesale of electrical household appliances",
  "46690": "Wholesale of other machinery and equipment",
  "46740": "Wholesale of hardware, plumbing and heating equipment",
  "46900": "Non-specialised wholesale trade",
  "47110": "Retail sale in non-specialised stores",
  "47190": "Other retail sale in non-specialised stores",
  "47540": "Retail sale of electrical household appliances",
  "47591": "Retail sale of furniture and lighting",
  "47599": "Retail sale of other household articles n.e.c.",
  "47789": "Other retail sale of new goods in specialised stores",
  "64200": "Activities of holding companies",
  "64209": "Activities of other holding companies",
  "66190": "Other activities auxiliary to financial services",
  "68100": "Buying and selling of own real estate",
  "68209": "Other letting and operating of own or leased real estate",
  "68310": "Real estate agencies",
  "69201": "Accounting and auditing activities",
  "70100": "Activities of head offices",
  "70210": "Public relations and communication activities",
  "70229": "Management consultancy activities other than financial management",
  "71111": "Architectural activities",
  "71121": "Engineering design activities for industrial process and production",
  "71122": "Engineering related scientific and technical consulting activities",
  "71129": "Other engineering activities",
  "71200": "Technical testing and analysis",
  "72190": "Other research and experimental development on natural sciences",
  "74909": "Other professional, scientific and technical activities n.e.c.",
  "77390": "Renting and leasing of other machinery and equipment",
  "80100": "Private security activities",
  "81100": "Combined facilities support activities",
  "81210": "General cleaning of buildings",
  "82110": "Combined office administrative service activities",
  "82990": "Other business support service activities n.e.c.",
  "85600": "Educational support activities",
  "96090": "Other service activities n.e.c.",
};

export function getSicDescription(code: string): string {
  return SIC_CODES[code] || code;
}
