// UK postcode area → county mapping
// Based on Royal Mail postcode areas

const POSTCODE_COUNTY: Record<string, string> = {
  // England
  "AB": "Aberdeenshire",
  "AL": "Hertfordshire",
  "B": "West Midlands",
  "BA": "Somerset",
  "BB": "Lancashire",
  "BD": "West Yorkshire",
  "BH": "Dorset",
  "BL": "Greater Manchester",
  "BN": "East Sussex",
  "BR": "Greater London",
  "BS": "Bristol",
  "BT": "Northern Ireland",
  "CA": "Cumbria",
  "CB": "Cambridgeshire",
  "CF": "Cardiff",
  "CH": "Cheshire",
  "CM": "Essex",
  "CO": "Essex",
  "CR": "Greater London",
  "CT": "Kent",
  "CV": "Warwickshire",
  "CW": "Cheshire",
  "DA": "Kent",
  "DD": "Dundee",
  "DE": "Derbyshire",
  "DG": "Dumfries and Galloway",
  "DH": "County Durham",
  "DL": "County Durham",
  "DN": "South Yorkshire",
  "DT": "Dorset",
  "DY": "West Midlands",
  "E": "Greater London",
  "EC": "Greater London",
  "EH": "Edinburgh",
  "EN": "Hertfordshire",
  "EX": "Devon",
  "FK": "Falkirk",
  "FY": "Lancashire",
  "G": "Glasgow",
  "GL": "Gloucestershire",
  "GU": "Surrey",
  "HA": "Greater London",
  "HD": "West Yorkshire",
  "HG": "North Yorkshire",
  "HP": "Buckinghamshire",
  "HR": "Herefordshire",
  "HS": "Outer Hebrides",
  "HU": "East Riding of Yorkshire",
  "HX": "West Yorkshire",
  "IG": "Greater London",
  "IP": "Suffolk",
  "IV": "Highland",
  "KA": "Ayrshire",
  "KT": "Surrey",
  "KW": "Highland",
  "KY": "Fife",
  "L": "Merseyside",
  "LA": "Lancashire",
  "LD": "Powys",
  "LE": "Leicestershire",
  "LL": "Gwynedd",
  "LN": "Lincolnshire",
  "LS": "West Yorkshire",
  "LU": "Bedfordshire",
  "M": "Greater Manchester",
  "ME": "Kent",
  "MK": "Buckinghamshire",
  "ML": "South Lanarkshire",
  "N": "Greater London",
  "NE": "Tyne and Wear",
  "NG": "Nottinghamshire",
  "NN": "Northamptonshire",
  "NP": "Newport",
  "NR": "Norfolk",
  "NW": "Greater London",
  "OL": "Greater Manchester",
  "OX": "Oxfordshire",
  "PA": "Renfrewshire",
  "PE": "Cambridgeshire",
  "PH": "Perth and Kinross",
  "PL": "Devon",
  "PO": "Hampshire",
  "PR": "Lancashire",
  "RG": "Berkshire",
  "RH": "Surrey",
  "RM": "Greater London",
  "S": "South Yorkshire",
  "SA": "Swansea",
  "SE": "Greater London",
  "SG": "Hertfordshire",
  "SK": "Cheshire",
  "SL": "Berkshire",
  "SM": "Greater London",
  "SN": "Wiltshire",
  "SO": "Hampshire",
  "SP": "Wiltshire",
  "SR": "Tyne and Wear",
  "SS": "Essex",
  "ST": "Staffordshire",
  "SW": "Greater London",
  "SY": "Shropshire",
  "TA": "Somerset",
  "TD": "Scottish Borders",
  "TF": "Shropshire",
  "TN": "Kent",
  "TQ": "Devon",
  "TR": "Cornwall",
  "TS": "North Yorkshire",
  "TW": "Greater London",
  "UB": "Greater London",
  "W": "Greater London",
  "WA": "Cheshire",
  "WC": "Greater London",
  "WD": "Hertfordshire",
  "WF": "West Yorkshire",
  "WN": "Greater Manchester",
  "WR": "Worcestershire",
  "WS": "West Midlands",
  "WV": "West Midlands",
  "YO": "North Yorkshire",
  "ZE": "Shetland Islands",
};

export function getCountyFromPostcode(postcode: string): string | null {
  if (!postcode) return null;
  const clean = postcode.trim().toUpperCase().replace(/\s+/g, "");

  // Try two-letter prefix first, then one-letter
  const twoLetter = clean.slice(0, 2);
  if (POSTCODE_COUNTY[twoLetter]) return POSTCODE_COUNTY[twoLetter];

  const oneLetter = clean.slice(0, 1);
  if (POSTCODE_COUNTY[oneLetter]) return POSTCODE_COUNTY[oneLetter];

  return null;
}
